export { default as Pravitelstvo } from './Pravitelstvo'
export { default as ZakonRFoPravkah } from './ZakonRFoPravkah'
export { default as PrikazFoiv } from './PrikazFoiv'
export { default as RasporyazheniePresidenta } from './RasporyazheniePresidenta'
export { default as RasporyazheniePravitelstva } from './RasporyazheniePravitelstva'
export { default as UkazPresidenta } from './UkazPresidenta'
export { default as FZ } from './FZ'
export { default as FKZ } from './FKZ'
